version: '3'

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 10s
      retries: 10
    env_file:
      - ./db/.env
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
  client:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile-local
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  server:
    restart: unless-stopped
    build:
      context: ./service
      dockerfile: Dockerfile-local
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./service/.env
    volumes:
      - ./service:/app
      - /app/node_modules
    ports:
      - "8080:8080"

