version: '3'

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - ./db/.env
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
  server:
    build:
      context: ./service
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./service/.env
    ports:
      - "8000:8000"

